### ISSUE TITLE
Designer can make standing area

### ISSUE THREAD

**Issue by DennisVargas** [WSUVCapstoneTeam7/SeatMapMaker#14]

**Comment by DennisVargas** [comment]
Standing areas are just seating sections that don't have any circles.

**Comment by amyphillips-wsuv** [comment]
I did this, right? Or is this referring to something else?

**Comment by DennisVargas** [comment]
Not sure if you were trying to close the issue but it only left the comment. 
I had proposed we add general seating as a radio button option that toggles in add seating.
this toggle would change the fields of column and row to be invisible leaving only Title. The submit handler would then need a condition statement if( generalRadio) runGeneralSeatingFunction. 
This was the idea with the radio's in the add seating section when I had originally proposed it months ago. This is really more to do with the issue [Create radio buttons in add seating that toggle between standing room and seated options. #17.](https://github.com/WSUVCapstoneTeam7/SeatMapMaker/issues/17) Also closely related is issue [Make table options invisible when radio buttons are selected. #21](https://github.com/WSUVCapstoneTeam7/SeatMapMaker/issues/21)

**Comment by amyphillips-wsuv** [comment]
I wasn't trying to close it yet, still want to add the ability to color the box. And this shouldn't be part of the other issues because even if we make standing area under seating we also need general areas to mark off other non-purchasable spaces. For example, the stage I had in the example I sent to Lang for the midterm check-in.

**Comment by amyphillips-wsuv** [comment]
General Area boxes can now be colored (must input hex value, but it works) and the box can be resized without distorting the text. That finishes up all my goals for this object. If there are no other, this can be closed.

**Comment by DennisVargas** [comment]
Excellent to hear.
