### ISSUE TITLE
Create a data representation of the map using the vue instance data variable.

### ISSUE THREAD

**Issue by DennisVargas** [WSUVCapstoneTeam7/SeatMapMaker#18]
Seat components will be VueJS components that hold the values for each seat so that they can be stored and used to manipulate and/or create fabric objects which will be the visual representation of each VueJS component.

**Comment by DennisVargas** [comment]
I'd like to figure out how to attach prices to the seat objects which at this moment or only fabric objects.

**Comment by DennisVargas** [comment]
mapData{} object may be used to hold this data object.
![image](https://user-images.githubusercontent.com/28330008/35487193-bb9d0ed2-042d-11e8-90bc-c078174c9b88.png)

**Comment by constitutionalFNRC** [comment]
I will likely look into this as an extension of seat pricing.

**Comment by DennisVargas** [comment]
mapData will have to be composed as seating sections are added. Adding one seating section should mutate mapData to look like
```
 mapData = {
      Sections:[ { 
       id:"TestName",
         Rows[{
           id:"A",
             Seats:[{
                id: 300,
                price: "100"
                fabCanvasObject: JSON.stringify(fabCanvas.getItem(circle))
             }]//seats
          }], //rows
         fabCanvasGroup: JSON.stringify(fabCanvas.getItem(square))
      }]
}
```

**Comment by DennisVargas** [comment]
this would be a single section with one row and one seat in that row.
This would then need to be written out to the seat-map.json as a string where the fabCanvasObject and fabCanvasGroup are stringified versions of the fabric object. MapData will be built from the seat-map.json file but be altered during the course of editing as items are added. When download gets clicked mapData composes itself. Its a more involved loading process becuase it requires the rebuilding of mapData rather than a simple loadFromJSON("seatmap.json").

**Comment by DennisVargas** [comment]
We should be able to compose mapData in mapSeating function.

**Comment by DennisVargas** [comment]
Chris Forked a "StackBlitz" prototype I began and the result can be seen at this link https://stackblitz.com/edit/seating-section-creator-z8qzt5

**Comment by DennisVargas** [comment]
Made a lot of progress on this. Every section type is being added to a group_price_array with elements of JSObject { price: 100, sectionFabricGroup: group};
Editing seats performs a delete and recreation of section groups so I will need to remove the old group and add the newly edited group. The same goes for Delete minus the re-adding the new group to the list.
