### ISSUE TITLE
Make table options invisible when radio buttons are selected.

### ISSUE THREAD

**Issue by DennisVargas** [WSUVCapstoneTeam7/SeatMapMaker#21]

**Comment by DennisVargas** [comment]
We can maybe setup a variables that tracks a boolean value whenever the radio button is selected. https://stackoverflow.com/questions/2272507/find-out-if-radio-button-is-checked-with-jquery

The variable can then be used in a V-show command.
https://vuejs.org/v2/guide/conditional.html#v-show

**Comment by DennisVargas** [comment]
We actually don't need jquery since the radio buttons are part of a vue template. They can be tied to a v-model variable like isSquare or isRound. This method is more direct and works just like any other Boolean toggle. The v-show condition when attached to an element toggles its visibility . ( <form v-show: "isSquare">Show square stuff as a form </form>.

**Comment by amyphillips-wsuv** [comment]
Closing this, I thought it was part of the table creation issue, which I just closed.
