### ISSUE TITLE
Click and drag on canvas background pans the view

### ISSUE THREAD

**Issue by DennisVargas** [WSUVCapstoneTeam7/SeatMapMaker#24]
Fabric has an option to drag the canvas surface and move it in it around to recenter your object to your view.
Implementing this would require setting limits for where the camera or whatever tracks view position.

**Comment by amyphillips-wsuv** [comment]
Canvas can be panned by clicking and dragging anywhere but on an object.

**Comment by DennisVargas** [comment]
Awesome Sauce!
