### ISSUE TITLE
Update canvas size on window resize event.

### ISSUE THREAD

**Issue by DennisVargas** [WSUVCapstoneTeam7/SeatMapMaker#25]
The fabric canvas needs to resize based on the window size. 
Whenever the map is loaded in a smaller than screen size resolution the canvas stays at that size.

**Comment by DennisVargas** [comment]
I found an old version of a nodeJS implementation of our project that had a window resize event handler. I didn't ever transfer this feature before because I was finding bugs that I don't think had to do with the window resizing. https://github.com/DennisVargas/Team7-WSUV-Capstone/blob/fc1691e5a5587f7920a093157ec93a5f7b68b61f/dennis_vuejs_tutorials/vueCLI_projects/SeatMapMakerTest/src/SeatMapMaker.vue

**Comment by DennisVargas** [comment]
![image](https://user-images.githubusercontent.com/28330008/38239982-241d4534-36e3-11e8-927d-8f802da256ed.png)

**Comment by DennisVargas** [comment]
this is on the vue instance mounted function. 
![image](https://user-images.githubusercontent.com/28330008/38240062-533a2652-36e3-11e8-9443-6629a6395007.png)

**Comment by DennisVargas** [comment]
202 adds the listener handler for resize to trigger the resizeFabCanvas.

**Comment by DennisVargas** [comment]
Not sure if this is complete haven't tested. Will do so tomorrow.

**Comment by amyphillips-wsuv** [comment]
Canvas now resizes when the window resizes.
