### ISSUE TITLE
User can disable individual seats

### ISSUE THREAD

**Issue by DennisVargas** [WSUVCapstoneTeam7/SeatMapMaker#28]

**Comment by DennisVargas** [comment]
I think once de-grouped the search for 
<code>
if !isGrouped and isCircleType:"check if this is the item selected" 
</code>
<code>
else: " goto next item on canvas"
</code> 
You're right this should give a good search result.

**Comment by DennisVargas** [comment]
https://github.com/kangax/fabric.js/issues/586 
Once you break apart the group you'll need to make the pieces immovable and select-able. The link above shows a method some one did to get this done. Doesn't seem to be a fabric.js method that provides this.

**Comment by amyphillips-wsuv** [comment]
I think this is the same as Issue 7: Designer can remove individual seats that don't exist.

**Comment by DennisVargas** [comment]
Right I created this when i found those resources. I missed issue 7, this info is irrelevant now since the solution to this issue has progressed passed this point. Closing now.
