### ISSUE TITLE
Increase the X value of where seating, general, and table objects initialize

### ISSUE THREAD

**Issue by DennisVargas** [WSUVCapstoneTeam7/SeatMapMaker#29]
These objects are currently appearing behind the menu making it unclear with small objects where they were created. If we increase the initial X values of where each item is created they will no longer spawn behind the menu.

**Comment by amyphillips-wsuv** [comment]
Objects now initialize to the right of the menu. I made to variables at the top of main.js that will change the start points for all objects, so if this needs to be done again it can be done easily.
