### ISSUE TITLE
Click on a seat in customer mode and have seat details appear.

### ISSUE THREAD

**Issue by DennisVargas** [WSUVCapstoneTeam7/SeatMapMaker#4]

**Comment by DennisVargas** [comment]
The box may be able to contain a buy option within it.

**Comment by amyphillips-wsuv** [comment]
Shouldn't this be on Seat Map Viewer?

**Comment by DennisVargas** [comment]
Yes correct. This is an issue leftover from my original transfer from our google doc. I then created the seat map viewer repo to handle this functionality but missed removing the issue here. 
The issue does exist on the viewer side and chris is working it out i believe. 
https://github.com/WSUVCapstoneTeam7/SeatMapViewer/issues/7
